### ISSUE TITLE
Changing titles

### ISSUE THREAD

**Issue by GAMINGCHATS** [LyGhT1337/DarknessCodeBlocks#1]
How do I go from 1 title to another? For example, how do I go from "Code" to "Python"

**Comment by YamsSE** [comment]
Usually it works with auto detection via discord, this doesn't work flawlessly sadly and needs some fixing from Discord's side.

But you can do it manually by putting the languages shortcut after using code.....

For example:

![image](https://user-images.githubusercontent.com/37241762/170981823-f46b9449-854b-40d4-b2cd-f3d88b1b0ce5.png)

results in:

![image](https://user-images.githubusercontent.com/37241762/170981859-e54694ff-01da-4473-80cf-ad3009ccb1c8.png)


but with "py" for python: 

![image](https://user-images.githubusercontent.com/37241762/170981950-df0d8734-da74-490d-a7a9-6185fb0975db.png)


Results in this:

![image](https://user-images.githubusercontent.com/37241762/170981994-0c411351-32d1-46eb-8414-0ec592714040.png)


And this goes and works for every other language... the complete list is below:

```
hljs
diff
cs
ini
autohotkey
asciidoc
TOML
nginx
perl
d
javascript
css
bash
markdown
html
xl
coffee
ruby
sql
java
py
vb
lua
php
swift
makefile
go
rust
prolog
ts
http
json
xml
less
sass
elm
cpp
hbs
\1c
abnf
clojure
objc
yml
shell
kotlin
apache
stylus
avrasm
llvm
mipsasm
x86asm
crmsh
dns
dockerfile
dsconfig
jbboss-cli
ldif
pf.conf
puppet
roboconf
axapta
cos
isbl
livecodeserver
ldif
ruleslanguage
clean
coq
elixir
erlang-repl
erlang
flix
fsharp
haskell
ocaml
scala
sml
xquery
glsl
mel
processing
rib
rsl
armasm
asm


```
